server:
  port: 10011

spring:
  datasource: #### 数据库连接池属性
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatistest?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
  profiles: ###当前配置模式
    active: test

# mybatis对应的映射文件路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # mybatis对应的实体类
  type-aliases-package: com.example.test.demo.mysql.model
